# .cirrus.yml

task:
  cron_job:
    cron: '* * * * *'  # Cron schedule (every Monday at 3 AM UTC)
    jobs:
      - build  # Specify the job to run on this schedule

# Define your jobs
build:
  container:
    image: circleci/node:22.11.0
  steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          npm install  # Install project dependencies
    - run:
        name: Crawl websites
        command: |
          node src/app.js

