# .cirrus.yml

task:
  build:
    docker:
      image: node:14  # Use the official Node.js Docker image (version 14)
    steps:
      - checkout  # Checkout the code from the GitHub repository
      - run:
          name: Install dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run tests
          command: npm test  # Run tests using npm
