version: 2.1

jobs:
  # Job to install dependencies
  install_dependencies:
    docker:
      - image: cimg/base:2024.05
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install  # Install project dependencies
          name: Crawl websites
          command: |
            node src/app.js

workflows:
  version: 2
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "* * * * *" 
          filters:
            branches:
              only: main  # Run this only on the 'main' branch
    jobs:
      - install_dependencies
      - Crawl websites
