version: 2.1

jobs:
  # Job to install dependencies
  crawl_websites:
    docker:
      - image: cimg/node:22.11.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install  # Install project dependencies
      - run:
          name: Crawl websites
          command: |
            node src/app.js

workflows:
  version: 2
  scheduled_workflow:
    triggers:
      - schedule:
          cron: "00 12 * * *" 
          filters:
            branches:
              only: main  # Run this only on the 'main' branch
    jobs:
      - crawl_websites